# Development Dockerfile for testing local Quibble changes.
#
# Installs your working copy of Quibble into the virtualenv that the CI
# image keeps Quibble in.
#
# Build:
# docker build --platform linux/amd64 -f docker/Dockerfile.dev -t quibble-dev .
#
# Check the README for how to run tests

FROM docker-registry.wikimedia.org/releng/quibble-bookworm-php83:latest

USER root

COPY . /opt/quibble
RUN "$QUIBBLE_VENV"/bin/pip install --no-cache-dir /opt/quibble

USER nobody

ENTRYPOINT ["quibble-with-supervisord"]
